### ISSUE TITLE
Please upload RPM package to release

### ISSUE THREAD

**Issue by jazzwang** [tenmax/azurekit#4]
Please upload RPM and DEB files to https://github.com/tenmax/azurekit/releases, thanks~
https://gist.github.com/jazzwang/b79d2a512514757a39174591af9291ef

End user could also install with YUM directly
```
sudo yum -y install https://gist.github.com/jazzwang/b79d2a512514757a39174591af9291ef/raw/a570b904d85724aa2733bb646dec69892c41fc95/azurekit-0.2.1-1.noarch.rpm
```

**Comment by phstudy** [comment]
Okay.
